### ISSUE TITLE
Build in Capability to Set Transparency of Materials for Simple Radiation Studies

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-dynamo#12]
It seems like it should if everything is being turned over to Radiance now, no?  See this discussion for more details:
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1517657&xg_source=msg

-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey with the daylight coefficient method that @sariths [is implementing](https://github.com/ladybug-analysis-tools/honeybee/issues/54) for honeybee implementing this will be a piece of cake.

PS: I think I can finally use this as an example of why I was pushing for using radiance daylight coefficient based radiation analysis for all the comfort models. There is actually much more that we can do for all the interior analysis too. It's all eventually coming together.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I agree and I am coming around to see a lot of the benefits too.  That sunlight hours example that you posted was very fast.
-Chris

**Comment by mostaphaRoudsari** [comment]
This is not related anymore as all the radiation analysis recipes are radiance-based and already capable of handling materials.
