### ISSUE TITLE
Curtain walls not being picked up / differentiating between glazed solid panels and exporting to Grasshopper -

### ISSUE THREAD

**Issue by antonszilasi** [ladybug-tools/honeybee-dynamo#20]
@mostaphaRoudsari 

I noticed that embedded curtain walls (Curtain walls embedded in basic walls) were not being picked up by convertRoomstoZone component however as soon as I changed the code here: https://github.com/antonszilasi/honeybeex/commit/0c7a6b868558bbced79e0065e0319844aa50edd8#diff-e692caba53dbe083b62e645153e173c0L57 it did start working.

Furthermore I noticed that there was no code to differentiate between solid or glazed panels I've written some code which I think works however I'm not sure how to export to Grasshopper to check. See the code here: https://github.com/antonszilasi/honeybeex/commit/0c7a6b868558bbced79e0065e0319844aa50edd8#diff-e692caba53dbe083b62e645153e173c0R107

Let me know what you think of these two changes

**Comment by mostaphaRoudsari** [comment]
@antonszilasi I know this issue is very old but is there any chance to you have the model that you used to create this issues? Thanks.

I started a new package to get this fixed. Doesn't seem the Autodesk API is going to support this feature anytime soon.

https://github.com/ladybug-tools/dynosaur

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  I'm afriad I don't I should have commited it!

**Comment by mostaphaRoudsari** [comment]
Hi @antonszilasi. It's cool. Thanks for the update.
