### ISSUE TITLE
The gh file called by test.py does not indicate if the error was a file path issue.

### ISSUE THREAD

**Issue by sariths** [ladybug-tools/honeybee-dynamo#5]
@mostaphaRoudsari ,

I just ran the test.py file and found that it didn't work the first time around as my path wasn't set. However, the sample.log file only says that "Number values are not as expected. 

Can we add these lines to the script that writes to the log file ?

![3-12-2016 6-23-34 pm](https://cloud.githubusercontent.com/assets/10361848/13725928/8ca1a104-e87f-11e5-8669-911afd047beb.png)

```
hbPath = sticky['hb_lib_path']
if not os.path.exists(hbPath):
    log.append("The Honeybee libraries were not found in %s"%hbPath)
```

**Comment by mostaphaRoudsari** [comment]
Hi @sariths! Great catch. I think we need to find all the components with error messages on the canvas and add their error report to the log file.

BTW my example file is not a good example for testing. I need to break it down into smaller files that tests only a single component.

**Comment by mostaphaRoudsari** [comment]
move to grasshopper repository
https://github.com/ladybug-tools/honeybee-grasshopper/issues/2
