### ISSUE TITLE
Honeybee in Dynamo versus Grasshopper

### ISSUE THREAD

**Issue by Mahamiho** [ladybug-tools/honeybee-dynamo#51]
Hey,
I developed a script in dynamo to test Honeybee, and I compared the results of the same model in Revit and simulation using Dynamo, to a model in rhino and simulation in grasshopper. However the results were much higher in Honeybee in Dynamo. I already have the same materials assigned and the same ambient bounces, and single glass pane in each window, and same legend threshold. Are there other things that I should check in Dynamo? Is there a script in Dynamo that I can use to simulate the DF and compare it to the script that I am using. I am now using an overcast sky, and then dividing the result illuminance by 10000 to calculate the DF.
Thanks in advance,

**Comment by mostaphaRoudsari** [comment]
@Mahamiho can you share your example files? I created a test case and the results are pretty similar.

**Comment by Mahamiho** [comment]
Hey Mostapha,
Thanks for your reply, I am preparing a 'clean script' that I can share because I was developing many things. In the meantime can you share the test script in a format compatible with version 1.2.1 in Dynamo because I could not open it. Thanks in advance,

**Comment by mostaphaRoudsari** [comment]
Hi @Mahamiho. Which test script are you referring to?

**Comment by Mahamiho** [comment]
Hey,
I tried to open the dynamo files in this link, is it possible to open them in dynamo version 1.2.1?
https://github.com/ladybug-tools/honeybee-plus/tree/master/test

**Comment by mostaphaRoudsari** [comment]
Try the files [here](https://github.com/ladybug-tools/honeybee-plus/tree/master/plugin/dynamo/samplefiles) which also comes with the installation.

**Comment by Mahamiho** [comment]
Hey Mostapha,
Thanks again for the help, I checked the files and updated my scripts. The result is the same in Dynamo and in Grasshopper, and I am uploading the result so that other people can view it too. I noticed however that these results was the same when I had a single glass layer in Honeybee, and normal double glass window in Dynamo, when I tested with a single surface in Dynamo the results were different. Was it also like that when you tested the script, or is it an error from my side?
![170515_result from the simple script_grasshopper](https://cloud.githubusercontent.com/assets/26859104/26306120/76a2a554-3ef2-11e7-91da-11cd4014e38b.PNG)

![170515_result from dynamo_all double glass_inner floor boundary](https://cloud.githubusercontent.com/assets/26859104/26306131/8161da00-3ef2-11e7-8b40-70d5df047cb6.PNG)

**Comment by mostaphaRoudsari** [comment]
Hi @Mahamiho, Single case glazing in both case should give you similar results. At the same time the current radiance parameters are set pretty low and that might have been the reason of the results discrepancy. I leave this discussion open for now until we expose the parameters and we can check both of them against each other with higher accuracy.

**Comment by Mahamiho** [comment]
Hey @mostaphaRoudsari,okey this is intersting to know, I think I will go through the script again and try to run it with different ambient bounces and see how much it will influence. Will post the updates this week or next week.

**Comment by sariths** [comment]
@Mahamiho Can you share the rad files for both the projects?

**Comment by Mahamiho** [comment]
Hey @sariths I am attaching the folders for the results from Grasshopper (using single glazing) and from Dynamo (using double glazing) so the ones used to generate the images above. thanks alot for the help in advance,
[170512_MSH_grasshopper.zip](https://github.com/ladybug-tools/honeybee-plus/files/1034088/170512_MSH_grasshopper.zip)

**Comment by sariths** [comment]
@Mahamiho I was hoping that the models were for the same room so that I could sun analytics on them to compare if the models themselves had anything to do with the difference in results.

**Comment by Mahamiho** [comment]
Hey @sariths I am attaching the folders when using single glass in both models, the result in dynamo when using single glass is below. Thanks alot.
[Comparing dynamo and honeybee.zip](https://github.com/ladybug-tools/honeybee-plus/files/1039639/Comparing.dynamo.and.honeybee.zip)
![170515_result from dynamo_all single glass](https://cloud.githubusercontent.com/assets/26859104/26603908/cf7610f2-4588-11e7-98e1-0779c263e9f0.PNG)

**Comment by sariths** [comment]
Hi @Mahamiho, I finally got around to analyzing your two models. The scene dimensions, as translated into Radiance by Grasshopper and Dynamo are not all that different.

~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*Grasshopper~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
```
     xmin      xmax      ymin      ymax      zmin      zmax
  -9.0826   21.5374  -19.7897   10.9836    -0.335     4.121
```

~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*Dynamo~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
```
     xmin      xmax      ymin      ymax      zmin      zmax
 -9.08262   21.5374  -19.6364   10.9836    -0.335     4.121
```
However, due to the different properties assigned in both cases you'd get different results for the same lighting conditions as shown below:

~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*Grasshopper~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*

![selection_268](https://cloud.githubusercontent.com/assets/10361848/26759011/3e0197ac-48be-11e7-91b2-94982a876f31.jpg)

~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*Dynamo~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
![selection_269](https://cloud.githubusercontent.com/assets/10361848/26759018/5b940c50-48be-11e7-948e-35ea38e6bc45.jpg)


Here is a summary of the Radiance model in both cases:
~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*Grasshopper~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
The primitives in this scene, sorted by modifier type and then modififer name, are:
~~~~~~~~~~~~~~~
Glass: glass
	void glass Glass 0 0 4 0.708 0.708 0.708 1.520
	3 surfaces
		polygon: 3
Ceiling: plastic
	void plastic Ceiling 0 0 5 0.700 0.700 0.700 0.000 0.050
	6 surfaces
		polygon: 6
Floor: plastic
	void plastic Floor 0 0 5 0.350 0.350 0.350 0.000 0.050
	21 surfaces
		polygon: 21
IntWalls: plastic
	void plastic IntWalls 0 0 5 0.700 0.700 0.700 0.000 0.050
	135 surfaces
		polygon: 135
Roof: plastic
	void plastic Roof 0 0 5 0.700 0.700 0.700 0.000 0.050
	6 surfaces
		polygon: 6
Windowframes: plastic
	void plastic Windowframes 0 0 5 0.800 0.800 0.800 0.000 0.050
	24 surfaces
		polygon: 24

~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*Dynamo~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
The primitives in this scene, sorted by modifier type and then modififer name, are:

~~~~
glass1: glass
	void glass glass1 0 0 3 0.708 0.708 0.708
	2 surfaces
		polygon: 2
generic_floor: plastic
	void plastic generic_floor 0 0 5 0.200 0.200 0.200 0.000 0.000
	319 surfaces
		polygon: 319
generic_roof: plastic
	void plastic generic_roof 0 0 5 0.800 0.800 0.800 0.000 0.000
	253 surfaces
		polygon: 253
generic_wall: plastic
	void plastic generic_wall 0 0 5 0.500 0.500 0.500 0.000 0.000
	654 surfaces
		polygon: 654

PS: It's not a good idea to over name the materials as the same name as Radiance keywords. 

I will address this in a separate issue with @mostaphaRoudsari

**Comment by Mahamiho** [comment]
Hey @sariths,
Thanks alot for your help in doing this analysis. I have a couple of questions though, 
- Do you perform this analysis in Radiance directly? which files do you use for the analysis is it only the rad file? Is there a document or tutorial that I can follow to be able to do it myself in the future?
- The main thing I noticed was that the primitives in dynamo are not full. I am sending you an email with all the details for it.
- Why would it be a problem to over-name the materials? would it be a problem in Radiance, or?
Thanks again,

**Comment by sariths** [comment]
Hi @Mahamiho, 

I a Radiance program called [objview](http://radsite.lbl.gov/radiance/man_html/objview.1.html) for viewing the files in 3D. The dimensions of the scene were calculated using [getbbox](http://radsite.lbl.gov/radiance/man_html/getbbox.1.html) (another Radiance program). The details of the scene (in terms of materials, surfaces etc) were listed using a couple of custom Python programs that I wrote for my research. Finally this entire set of operations itself was run in a couple of seconds using a top level script. 

Overnaming isn't an issue but naming materials the same as Radiance primitives can lead to problems.  You can find the list of Radiance primitives on this page: http://radsite.lbl.gov/radiance/refer/ray.html

Even though it is nearly two decades old, [Rendering With Radiance](https://www.amazon.com/Rendering-Radiance-Kaufmann-Computer-Graphics/dp/1558604995) is sitll the best resource to learn Radiance.

**Comment by mostaphaRoudsari** [comment]
@sariths and @Mahamiho, 

What is the status on this? Since we are updating all the nodes in Dynamo based on Grasshopper components everything will be the same. I go ahead and  close this issue for now.

@Mahamiho feel free to open a new issue if you have any follow up question.
