### ISSUE TITLE
Room to HBZones - Honeybee for Dynamo

### ISSUE THREAD

**Issue by andreameneg** [ladybug-tools/honeybee-dynamo#67]
I am doing some test on Honeybee for Dynamo  using some basic rooms geometry to test Sunlight Hours Analysis. 
Most of the time even with simple geometry the node "Room to HBZones" gives me an error:
- "index out of range:2" or "spatial element is not inclosed in 2d or has no location, or the height is too small, and thus has no 3D geometry to calculate;

I have verified that rooms have 2.40 meter height but I can't undestand how they seam to be includes in 2d if. There is anything that need to cheched before running the node? I have tried also with spaces instead of room but is not alwayas working.
![image](https://user-images.githubusercontent.com/31241257/29560564-a65570b4-8732-11e7-9599-df147bc7707b.png)

Thanks for your help @mostaphaRoudsari 
Andrea

**Comment by mostaphaRoudsari** [comment]
@andreameneg in the volume calculation set to Area and Volumes?
![image](https://user-images.githubusercontent.com/2915573/29574515-cb6cd26e-872f-11e7-9a56-5179c3729a23.png)

Also see [this](https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Revit-Model/files/GUID-84D8BC77-AAF3-4F45-B77E-58E35858D3AA-htm.html).

**Comment by andreameneg** [comment]
Yes,it is selected "Area and Volumes". There problem was with a Unbounded room in another project phase. 

Thanks

**Comment by mostaphaRoudsari** [comment]
Thanks for the update. Let's close this issue then.
