### ISSUE TITLE
a python problom in ladybug eather in grasshopper or dynamo

### ISSUE THREAD

**Issue by sajjadsaeedi** [ladybug-tools/honeybee-dynamo#68]
Hi

I have a problem to load this python component at dynamo canvas , what can I do solve this error permenently ?

that’s odd to say that in ladybug and honeybee plugin I have such this error too !

and I am sure if I get rid of dynamo error I will get rid of ladybug error too . because both of them are related to python or ironpython 
![3d510fb0ce002a80c2766ab8ea41b9cb5b8b2808_1_690x262](https://user-images.githubusercontent.com/31283604/29623110-8f230ab0-883a-11e7-8417-645f1ae54eba.png)
![6804db48d2885e3353a913596f0315a2dce11c67_1_433x500](https://user-images.githubusercontent.com/31283604/29623116-96f0bcce-883a-11e7-9bee-ce8a13680f71.png)

**Comment by mostaphaRoudsari** [comment]
@sajjadsaeedi I'm not sure what are you trying to do. If it is about using ladybug and honeybee in Dynamo install the packages from the package manager.

**Comment by sajjadsaeedi** [comment]
Hi
yes, percisely. I'm using ladybug and honeybee in dynamo. unfortunately I see this error only when I use ladybug components which is related to python or maybe was made in python !
thanks for your attention

**Comment by mostaphaRoudsari** [comment]
@sajjadsaeedi, let's start checking the process step by step:

1. Can you confirm that you have the latest version of the packages installed? Also Dynamo version is 1.3 or higher?
 ![screenshot 5](https://user-images.githubusercontent.com/2915573/29635452-19cb578c-881b-11e7-9bf0-6e8718e550cd.png)

2. Download [this example file](http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Import_EPW_Ladybug_Dynamo&slide=0&scale=1&offset=0,0) and let me know what is exactly the error message.

**Comment by sajjadsaeedi** [comment]
1. my ladybug version is 0.1.5 and my honeybee version is 0.1.2
2.I did that and here is the run of that file.
![capture2](https://user-images.githubusercontent.com/31283604/29638421-7e7b8d4a-886c-11e7-8e58-49a5bb41f31e.png)

**Comment by mostaphaRoudsari** [comment]
Thanks for sharing the screen. Based on the image everything is working as expected. You need to select a valid weather file. You can see the error message in the bottom right of the screen.

**Comment by sajjadsaeedi** [comment]
you're wellcom dear Mostafa. that's thanks to you for your attention. so what's the main reason for this problem ???
![6804db48d2885e3353a913596f0315a2dce11c67_1_433x500](https://user-images.githubusercontent.com/31283604/29639261-67e9884a-886f-11e7-942c-7a309a09514a.png)

**Comment by mostaphaRoudsari** [comment]
both nodes look fine. You need to write a code inside the node to get it to work. For the firs node you need a python script. That is a Dynamo question and you should send it to the Dynamo forum: https://forum.dynamobim.com/

Also check their tutorials!

**Comment by sajjadsaeedi** [comment]
yes, tnx.
this is my last question :
Do you know why these components are in red ?  I can't simulate in ladybug of rhino because of that problem!
![3d510fb0ce002a80c2766ab8ea41b9cb5b8b2808_1_690x262](https://user-images.githubusercontent.com/31283604/29640172-dc889b84-8872-11e7-927f-2c8486266072.png)

**Comment by mostaphaRoudsari** [comment]
Most probably you have an older version of GHPython. See this discussion: http://www.grasshopper3d.com/group/ladybug/forum/topics/ladybug-installation-problems

**Comment by sajjadsaeedi** [comment]
again it can't get rid of this problem :( 
tnx

**Comment by sajjadsaeedi** [comment]
Hi
to my genius friend
![definition](https://user-images.githubusercontent.com/31283604/30524182-afdbc0d6-9ba3-11e7-963e-6f13818d3cbd.jpg)
. I have a question.
how can I achieve “color surface” component which has _analysisSurfaces ?

It seems that we cant download that, via search packages. I tried.

**Comment by sajjadsaeedi** [comment]
I mean the last component which is the right side.

**Comment by sajjadsaeedi** [comment]
![23](https://user-images.githubusercontent.com/31283604/31864546-84935da4-b713-11e7-81eb-86349ec88874.png)

hi
why this error appear ???
tnx

**Comment by mostaphaRoudsari** [comment]
duplicated with this: https://github.com/ladybug-tools/honeybee-dynamo/issues/75
