### ISSUE TITLE
Annual Calcs - Empty results file

### ISSUE THREAD

**Issue by schaggar16** [ladybug-tools/honeybee-dynamo#70]
I am trying to the 2 samples scripts for annual daylight and annual radiation. For both i keep getting the error empty results file. 
When running the daylight one i got the error the rcontrib.exe stopped working. i am running Radiance 5.0 and latest honeybee packages.

**Comment by andreameneg** [comment]
I am experiencing the same issue. Apparently radiance in not writing the demo.ill files correcly.
Here is the error message: 

Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "C:\Users\XXX\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\solaraccess\gridbased.py", line 350, in results
    analysisGrid.setValuesFromFile(
  File "C:\Users\XXX\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\analysisgrid.py", line 245, in setValuesFromFile
    raise EmptyFileError(filePath)
EmptyFileError: Failed to load the results form an empty file: C:\Users\XXX\_Dynamo\Ladybug\Honeybee Test\demo\demo\solaraccess\result\demo.ill
Double check inputs and outputs and make sure everything is run correctly.

Thanks
Andrea

**Comment by samykbs** [comment]
Hi andrea

Thats the same issue i been trying to solve, have you find a solution for this? im still tryin to figure it out.

Thanks

**Comment by andreameneg** [comment]
Hi Samykbs,

I have solved it by simply installing Radiance in C:/Radiance and not in a custom folder path.

Best
Andrea

**Comment by schaggar16** [comment]
hi @andreameneg , i have got radiance installed in C:/radiance - still get the issue. any other ideas?

**Comment by samykbs** [comment]
Hi @schaggar16 same thing in my case I have installed radiance in C:\Radiance and i get the same issue, what im thinking is that it may be something related to the computer permissions or access, if i find something i let you know.

Also Thanks @andreameneg for the feedback =D

**Comment by samykbs** [comment]
Hey i figure out that is you install radiance in both C and tehn in Program files the analysis is running properly, Hope is helpful

**Comment by schaggar16** [comment]
@samykbs - thanks for the suggestion but no luck. i did some digging and have found that my sun_dynamo_sample_files..scene..default.dc file contains no data. 
my sunmtx.sun file looks like the following - is this correct? i am using a energyplus weather file so i imagine that should be the issue. 
![image](https://user-images.githubusercontent.com/20593879/30655440-d064b448-9e28-11e7-9fb1-467b9eb08097.png)

**Comment by mostaphaRoudsari** [comment]
> When running the daylight one i got the error the rcontrib.exe stopped working. i am running Radiance 5.0 and latest honeybee packages.

This is because you're using an older version of Radiance. Install [the latest version](https://github.com/NREL/Radiance/releases/tag/5.1.0) under `c:\radiance` and not `c:\Program Files\radiance` and the issue will be solved.

**Comment by schaggar16** [comment]
That did the trick. Thanks.
