### ISSUE TITLE
The Rooms to HBZone fails with message "There were not enough edges to form a polygon"

### ISSUE THREAD

**Issue by mdp79** [ladybug-tools/honeybee-dynamo#71]
Hey. Thanks for the great work with Honeybee Ladybug.

However I have stumpled upon a problem, that might/might not be a bug. It comes when making Rooms into Honeybee Zones. At least in some cases. It comes up with the following error message:

![image](https://user-images.githubusercontent.com/31468507/30535005-dd1e457e-9c60-11e7-9d6f-554f49770db2.png)

However it appears that it only come in some cases. I have previously used the same recipe in other projects where it works for most rooms, but come up with a similar error on maybe a single room.

So very curious to know if others have had the problem or I have overseen something somewhere in my model(s)

**Comment by mostaphaRoudsari** [comment]
@mdp79 thank you for posting this issue. I started a new package to address this issue: https://github.com/ladybug-tools/dynosaur

Can you share the problematic revit model with me?

**Comment by mdp79** [comment]
Ok. Sounds cool with Dynasour

Here is an example Revit file.
[DagslysDynamo_2017.zip](https://github.com/ladybug-tools/honeybee-dynamo/files/1347128/DagslysDynamo_2017.zip)
It's not the same as in the screen dumb but shows same error. I started out testing it with just one room and it worked there but after adding a wall making two rooms the same error occur. However, it is only in one of the rooms. The same happens in other models I tried it with.

Furthermore you'll find the Dynamo file and be aware that the Archilab_Grimshaw elements used have been updated to convert to metric system.

**Comment by mostaphaRoudsari** [comment]
Hi @mdp79, Thanks for sharing the model. Dynosaur successfully imports the rooms from your model. The top height needs to be adjusted to match the roof otherwise it looks good!

![image](https://user-images.githubusercontent.com/2915573/31060585-22632356-a6e4-11e7-818c-56d1ddf0cc4a.png)

I close this issue for now understanding that it will still be an issue until I integrate the new code into honeybee for dynamo.
