### ISSUE TITLE
Generate Colors Node 00_point_in_time_gridbased.dyn

### ISSUE THREAD

**Issue by MattWashBVN** [ladybug-tools/honeybee-dynamo#72]
Hi,
I am getting an error from the colors output of the generate colors node. I think it has something to do with the format of the color values. I have replace this node with a colorByARGB node to test and it runs successfully. The error I get from the Display.ByGeometryColor node is "Warning: One or more of the input types are not matching. Couldn't find a version of ByGeometryColor that takes arguments of type (__array,__array)". I have opened up the generate colors custom node and tried to see what the python script was looking for, but it is beyond my python knowledge to work out what might be causing the error. please can you help. See attached screenshot...thanks, Matt
![generatecolorsoutputerror](https://user-images.githubusercontent.com/32156296/30721407-42f74c72-9f6f-11e7-8d80-96b33a09b431.png)

**Comment by mostaphaRoudsari** [comment]
Hi @MattWashBVN, From your screenshot the issue is that the structure of the colors and geometries are different. Can you flatten both inputs before connecting them to Display.ByGeometryColor?

**Comment by bwlosinski** [comment]
We ran into this issue in the 04 example  and we had to flatten the lists and then unwrap the rgb values using a quick python node calling each value into a separate list and key them into a color.byargb node.
![honeybee_dynamo_rgbvalues](https://user-images.githubusercontent.com/19575091/32254044-65041e96-be6c-11e7-979a-9e6aef65aa00.PNG)

**Comment by mostaphaRoudsari** [comment]
@bwlosinski interesting! In your example the node fails to convert the colors from Ladybug colors to Dynamo colors. Are you using the latest version of Ladybug for Dynamo?

**Comment by mostaphaRoudsari** [comment]
I can't replicate this issue in the new release. Feel free to reopen the issue with a sample file to recreate the issue.
