### ISSUE TITLE
Honeybee Surface Error - invalid integer literal

### ISSUE THREAD

**Issue by schaggar16** [ladybug-tools/honeybee-dynamo#77]
Hi, currently getting the following error with the Honeybee Surface node, invalid integer literal (screenshot below). I am running latest version of honeybee and version 1.2.1 of dynamo with revit 2017.  
Any ideas?
![image](https://user-images.githubusercontent.com/20593879/33993643-4b0808a6-e0cf-11e7-8d21-b3aa6b826f19.png)

**Comment by mostaphaRoudsari** [comment]
Hmm. I remember we had this issue before. Any chance that you an share the full error message with me? I want to get the exact line that the error happens. Does it work if you remove type or names input?

**Comment by schaggar16** [comment]
Hi @mostaphaRoudsari - did some further digging into the errors, it was to do with the honeybee config file and my recent installation of openstudio. It was struggling with the location of the openstudio install. I have done a manual override to point it to the right location and it did the trick.

**Comment by mostaphaRoudsari** [comment]
Hi @schaggar16, Thank you for the update. Just for the future reference you can set up them manually inside config.json file which you can find inside the installation folder:
![image](https://user-images.githubusercontent.com/2915573/34001754-d3182e1c-e0be-11e7-8a8b-003ca1950baf.png)
