### ISSUE TITLE
which modeldoes ladybug use to calculate global radiation ?

### ISSUE THREAD

**Issue by koubaaleila** [ladybug-tools/honeybee-dynamo#78]
there is many models of calculation of global solar radiation ( Lacis &
Hansen, le modèle de Davies & Hay, le modèle de Bird & Hulstrom et celui de Atwater
& Ball ) which one does ladybug use?

**Comment by mostaphaRoudsari** [comment]
We are using Radiance to generate the skies. You can check the source code and the documentation from Radiance. For point in time radiation analysis you can use gensky ([docs](https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/gensky.pdf/view), [source](https://github.com/NREL/Radiance/blob/53485a7fb48727293d62f98d7bac830aa34ccba4/src/gen/gensky.c)) or gendaylit ([docs](https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/gendaylit.pdf/view), [source](https://github.com/NREL/Radiance/blob/53485a7fb48727293d62f98d7bac830aa34ccba4/src/gen/gendaylit.c)). If you use Honeybee for annual analysis then it is using gendaymtx ([docs](https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/gendaymtx.pdf/view), [source](https://github.com/NREL/Radiance/blob/53485a7fb48727293d62f98d7bac830aa34ccba4/src/gen/gendaymtx.c)).

**Comment by koubaaleila** [comment]
I used ladybug 1.7 for solar radiation analysis but when the componment is moved to honeybee i cannot calculate solar radiation. I have errors!!
![honeybee error](https://user-images.githubusercontent.com/24694950/35849674-af700d3e-0b22-11e8-9a96-b6e402dbe993.png)
why honeybee doesn't  distinguish between componment for solar radiation analysis and daylight analysis ?

**Comment by mostaphaRoudsari** [comment]
Hi @koubaaleila, Sorry for the delay to reply but the right place to post questions like this is discourse.ladybug.tools

I replied to your question under another similar issue.
