### ISSUE TITLE
solar radiation errors on honeybee

### ISSUE THREAD

**Issue by koubaaleila** [ladybug-tools/honeybee-dynamo#79]
hello!
I can't have values of solar radiation using honeybee! There is an error somewhere! Can you check it?
i'm using tunisia epw, ladybug 1.9, honeybee 1.5 on dynamo 1.3 and revit 2018

![capture](https://user-images.githubusercontent.com/24694950/34712830-843cec4a-f524-11e7-95ff-252c52853f5e.png)

**Comment by mostaphaRoudsari** [comment]
duplicate with #80
